In [3]:
import numpy as np
np.randomseed(12345)

In [7]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
print(type(my_arr))
my_arr.shape

<class 'numpy.ndarray'>


(1000000,)

In [13]:
my_list[1:5]*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
my_list[1:5] + my_list[1:5]

[1, 2, 3, 4, 1, 2, 3, 4]

In [11]:
L1 = [1,2,3]
L2 = [5,6,7]
L1+L2

[1, 2, 3, 5, 6, 7]

In [14]:
L1*L2

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 62.5 ms
Wall time: 2.28 s


## The NumPy ndarray: A multidimesional array object

In [22]:
import numpy as np
#Generate some random data
data = np.random.randn(2,3)
data

array([[ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962]])

In [23]:
data.shape#Prints the size of the array

(2, 3)

In [24]:
data * 10

array([[  0.9291,   2.8175,   7.6902],
       [ 12.4643,  10.0719, -12.9622]])

In [25]:
data + data

array([[ 0.1858,  0.5635,  1.538 ],
       [ 2.4929,  2.0144, -2.5924]])

In [26]:
data.dtype#Shows the type of the data in the array

dtype('float64')

## Creating ndarrays

In [28]:
#data1 = [6, 7.5, 8, 0, 1]
data1 = [0.001, 0.2, 0.3, 0.8]
arr1 = np.array(data1)
print( arr1 ) 
data2 = [0.1, 0.7, 0.7, 0.8]
arr2 = np.array(data2)
print( arr2 )
print(arr1.shape, arr2.shape)
print( "-:", arr2 - arr1) # subtraction
print( "/:", arr2 / arr1) # division
print( "+:", arr2 + arr1) # sum
#print( "*:", arr2 * arr1 ) # dot product

[0.001 0.2   0.3   0.8  ]
[0.1 0.7 0.7 0.8]
(4,) (4,)
-: [0.099 0.5   0.4   0.   ]
/: [100.       3.5      2.3333   1.    ]
+: [0.101 0.9   1.    1.6  ]


In [29]:
print( "*:", arr2 * arr1 ) # dot product

*: [0.0001 0.14   0.21   0.64  ]


In [30]:
np.matmul(arr1,arr2.transpose())#Matrix Multipliction

0.9901000000000001

In [31]:
np.matmul(arr1.transpose(),arr2)

0.9901000000000001

In [34]:
print(arr1.shape)
print(arr1.transpose(),arr1.shape)
print(arr2.shape)

(4,)
[0.001 0.2   0.3   0.8  ] (4,)
(4,)


In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [41]:
arr = np.array([1.5,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
float_arr.dtype

float64


dtype('float64')

In [44]:
arr = np.array([3.2,-1.5,-2.5,.5,12.9,10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [46]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
print(calibers)
int_array.astype(calibers.dtype)

[0 1 2 3 4 5 6 7 8 9]
[0.22  0.27  0.357 0.38  0.44  0.5  ]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithematic with NumPy arrays

In [47]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
#arr = np.array([[1., 2.], [4., 5.]])
print(arr)
arr * arr

[[1. 2. 3.]
 [4. 5. 6.]]


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [49]:
arr ** .5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

## Basic Indexing and Slicing

In [50]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:6])
arr[5:8] = 12
arr

[0 1 2 3 4 5 6 7 8 9]
5
[5]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [51]:
arr[5:8] = [.1,.2,.3]
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [53]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     0, 12345,     0,     8,
           9])

In [54]:
arr_slice

array([    0, 12345,     0])

In [56]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [58]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])